# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b9eaf372995775abf813216c9926d0e263bd3439cbaff26f8d54448e3d069eee2b5f8810d8cd9c579eea8c4872196c1a0f3f6a24ab223ad079657570e1c3dff

test:
  secret_key_base: ed912adc6607c734944621d4197803987bc8c6671c270b5de3ff1af097a69ffe6b0af79ad18b5613918c9d6247550862d9419523ac5ff6017d41ab21eda12217

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
